#!/bin/bash

# 手动下载 Microbit hex 文件的脚本
# 当自动下载失败时使用此脚本

set -e

echo "=== Scratch Editor Microbit 手动下载脚本 ==="
echo ""

# 检查是否在正确的目录
if [ ! -f "package.json" ]; then
    echo "错误：请在 scratch-editor 根目录运行此脚本"
    exit 1
fi

# 设置变量
DOWNLOAD_URL="https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip"
TEMP_DIR="/tmp/scratch-microbit-download"
TARGET_DIR="packages/scratch-gui/static/microbit"
GENERATED_DIR="packages/scratch-gui/src/generated"
GENERATED_FILE="$GENERATED_DIR/microbit-hex-url.cjs"

echo "下载URL: $DOWNLOAD_URL"
echo "目标目录: $TARGET_DIR"
echo ""

# 创建临时目录
echo "创建临时目录..."
rm -rf "$TEMP_DIR"
mkdir -p "$TEMP_DIR"

# 下载文件
echo "正在下载 microbit hex 文件..."
if command -v curl >/dev/null 2>&1; then
    curl -L -o "$TEMP_DIR/scratch-microbit.hex.zip" "$DOWNLOAD_URL"
elif command -v wget >/dev/null 2>&1; then
    wget -O "$TEMP_DIR/scratch-microbit.hex.zip" "$DOWNLOAD_URL"
else
    echo "错误：需要 curl 或 wget 来下载文件"
    exit 1
fi

echo "下载完成！"

# 解压文件
echo "正在解压文件..."
cd "$TEMP_DIR"
unzip -q scratch-microbit.hex.zip

# 查找 .hex 文件
HEX_FILE=$(find . -name "*.hex" | head -n 1)
if [ -z "$HEX_FILE" ]; then
    echo "错误：在下载的zip文件中未找到 .hex 文件"
    exit 1
fi

echo "找到 hex 文件: $HEX_FILE"

# 创建目标目录
echo "创建目标目录..."
cd - > /dev/null
mkdir -p "$TARGET_DIR"

# 复制文件
echo "复制文件到目标目录..."
cp "$TEMP_DIR/$HEX_FILE" "$TARGET_DIR/"

# 生成 require 文件
echo "生成 require 文件..."
mkdir -p "$GENERATED_DIR"

HEX_FILENAME=$(basename "$HEX_FILE")
REQUIRE_PATH="./static/microbit/$HEX_FILENAME"

cat > "$GENERATED_FILE" << EOF
// This file is generated by scripts/manual-microbit-download.sh
// Do not edit this file directly
// This file relies on a loader to turn this \`require\` into a URL
module.exports = require('$REQUIRE_PATH');
EOF

echo "生成文件: $GENERATED_FILE"

# 清理临时文件
echo "清理临时文件..."
rm -rf "$TEMP_DIR"

echo ""
echo "=== 手动下载完成！ ==="
echo "现在可以重新运行 npm install 了"
echo ""
