// From the NPM docs:
// "If you need to perform operations on your package before it is used, in a way that is not dependent on the
// operating system or architecture of the target system, use a prepare script."
// Once this step is complete, a developer should be able to work without an Internet connection.
// See also: https://docs.npmjs.com/cli/using-npm/scripts

import fs from 'fs';
import path from 'path';

import yauzl from 'yauzl';
import {fileURLToPath} from 'url';

// 为Node.js v16兼容性导入fetch
import fetch from 'node-fetch';

/** @typedef {import('yauzl').Entry} ZipEntry */
/** @typedef {import('yauzl').ZipFile} ZipFile */

// these aren't set in ESM mode
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// base/root path for the project
const basePath = path.join(__dirname, '..');

/**
 * Extract the first matching file from a zip buffer.
 * The path within the zip file is ignored: the destination path is `${destinationDirectory}/${basename(entry.name)}`.
 * Prints warnings if more than one matching file is found.
 * @param {function(ZipEntry): boolean} filter Returns true if the entry should be extracted.
 * @param {string} relativeDestDir The directory to extract to, relative to `basePath`.
 * @param {Buffer} zipBuffer A buffer containing the zip file.
 * @returns {Promise<string>} A Promise for the base name of the written file (without directory).
 */
const extractFirstMatchingFile = (filter, relativeDestDir, zipBuffer) => new Promise((resolve, reject) => {
    try {
        let extractedFileName;
        yauzl.fromBuffer(zipBuffer, {lazyEntries: true}, (zipError, zipfile) => {
            if (zipError) {
                throw zipError;
            }
            zipfile.readEntry();
            zipfile.on('end', () => {
                resolve(extractedFileName);
            });
            zipfile.on('entry', entry => {
                if (!filter(entry)) {
                    // ignore non-matching file
                    return zipfile.readEntry();
                }
                if (extractedFileName) {
                    console.warn(`Multiple matching files found. Ignoring: ${entry.fileName}`);
                    return zipfile.readEntry();
                }
                extractedFileName = entry.fileName;
                console.info(`Found matching file: ${entry.fileName}`);
                zipfile.openReadStream(entry, (fileError, readStream) => {
                    if (fileError) {
                        throw fileError;
                    }
                    const baseName = path.basename(entry.fileName);
                    const relativeDestFile = path.join(relativeDestDir, baseName);
                    console.info(`Extracting ${relativeDestFile}`);
                    const absoluteDestDir = path.join(basePath, relativeDestDir);
                    fs.mkdirSync(absoluteDestDir, {recursive: true});
                    const absoluteDestFile = path.join(basePath, relativeDestFile);
                    const outStream = fs.createWriteStream(absoluteDestFile);
                    readStream.on('end', () => {
                        outStream.close();
                        zipfile.readEntry();
                    });
                    readStream.pipe(outStream);
                });
            });
        });
    } catch (error) {
        reject(error);
    }
});

const downloadMicrobitHex = async () => {
    const relativeHexDir = path.join('static', 'microbit');
    const relativeGeneratedDir = path.join('src', 'generated');
    const relativeGeneratedFile = path.join(relativeGeneratedDir, 'microbit-hex-url.cjs');
    const absoluteHexDir = path.join(basePath, relativeHexDir);
    const absoluteGeneratedDir = path.join(basePath, relativeGeneratedDir);
    const absoluteGeneratedFile = path.join(basePath, relativeGeneratedFile);
    
    // 检查是否已经有hex文件存在
    if (fs.existsSync(absoluteHexDir)) {
        const hexFiles = fs.readdirSync(absoluteHexDir).filter(file => file.endsWith('.hex'));
        if (hexFiles.length > 0) {
            const hexFileName = hexFiles[0];
            console.info(`Found existing hex file: ${hexFileName}`);
            
            // 生成require文件
            fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
            const relativeHexFile = path.join(relativeHexDir, hexFileName);
            const requirePath = `./${path
                .relative(relativeGeneratedDir, relativeHexFile)
                .split(path.win32.sep)
                .join(path.posix.sep)}`;
            fs.writeFileSync(
                absoluteGeneratedFile,
                [
                    '// This file is generated by scripts/prepare.mjs',
                    '// Do not edit this file directly',
                    '// This file relies on a loader to turn this `require` into a URL',
                    `module.exports = require('${requirePath}');`,
                    '' // final newline
                ].join('\n')
            );
            console.info(`Wrote ${relativeGeneratedFile}`);
            return; // 文件已存在，跳过下载
        }
    }
    
    // 如果没有现有文件，尝试下载
    const url = 'https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip';
    console.info(`Downloading ${url}`);
    
    // 添加重试机制
    const maxRetries = 3;
    let lastError;
    
    for (let attempt = 1; attempt <= maxRetries; attempt++) {
        try {
            console.info(`Attempt ${attempt}/${maxRetries}`);
            const response = await fetch(url, {
                timeout: 30000, // 30秒超时
                headers: {
                    'User-Agent': 'Mozilla/5.0 (compatible; Scratch-Editor/1.0)'
                }
            });
            
            if (!response.ok) {
                throw new Error(`HTTP ${response.status}: ${response.statusText}`);
            }
            
            const zipBuffer = Buffer.from(await response.arrayBuffer());
            console.info(`Download successful on attempt ${attempt}`);
            
            const hexFileName = await extractFirstMatchingFile(
                entry => /\.hex$/.test(entry.fileName),
                path.join('static', 'microbit'),
                zipBuffer
            );
            const relativeHexFile = path.join(relativeHexDir, hexFileName);
            fs.mkdirSync(absoluteGeneratedDir, {recursive: true});
            const requirePath = `./${path
                .relative(relativeGeneratedDir, relativeHexFile)
                .split(path.win32.sep)
                .join(path.posix.sep)}`;
            fs.writeFileSync(
                absoluteGeneratedFile,
                [
                    '// This file is generated by scripts/prepare.mjs',
                    '// Do not edit this file directly',
                    '// This file relies on a loader to turn this `require` into a URL',
                    `module.exports = require('${requirePath}');`,
                    '' // final newline
                ].join('\n')
            );
            console.info(`Wrote ${relativeGeneratedFile}`);
            return; // 成功完成，退出函数
        } catch (error) {
            lastError = error;
            console.warn(`Attempt ${attempt} failed: ${error.message}`);
            
            if (attempt < maxRetries) {
                const delay = Math.pow(2, attempt) * 1000; // 指数退避：2秒，4秒，8秒
                console.info(`Retrying in ${delay/1000} seconds...`);
                await new Promise(resolve => setTimeout(resolve, delay));
            }
        }
    }
    
    // 所有重试都失败了
    console.error(`Failed to download after ${maxRetries} attempts. Last error: ${lastError.message}`);
    console.error('\n手动下载解决方案：');
    console.error('1. 手动下载文件：https://downloads.scratch.mit.edu/microbit/scratch-microbit.hex.zip');
    console.error('2. 解压到 packages/scratch-gui/static/microbit/ 目录');
    console.error('3. 重新运行 npm install');
    throw lastError;
};

const prepare = async () => {
    await downloadMicrobitHex();
};

prepare().then(
    () => {
        console.info('Prepare script complete');
        process.exit(0);
    },
    e => {
        console.error(e);
        process.exit(1);
    }
);
